# Generated by Django 5.1.4 on 2025-01-07 02:06

import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloWorld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTypeInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookTypeName', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '圖書類別信息',
                'db_table': 't_booktype',
            },
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=20)),
                ('publishDate', models.DateField()),
                ('price', models.FloatField()),
                ('bookType', models.ForeignKey(on_delete=django.db.models.query.Prefetch, to='HelloWorld.booktypeinfo')),
            ],
            options={
                'verbose_name': '圖書信息',
                'db_table': 't_book',
            },
        ),
    ]
