# Generated by Django 5.1.4 on 2025-01-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelloWorld', '0003_accountinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountinfo',
            options={'verbose_name': '用戶賬戶信息'},
        ),
        migrations.AlterModelTable(
            name='accountinfo',
            table='t_account',
        ),
    ]
